name: foodb_test
description: Test suite to run against different flavour of foodb
version: 0.13.0-3.7
repository: https://github.com/feedmepos/foodb 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  dotenv: ^3.0.0
  foodb: 0.13.0-3.7

dev_dependencies:
  pedantic: ^1.10.0
