name: foodb_test
description: Test suite to run against different flavour of foodb
version: 0.13.0
repository: https://github.com/feedmepos/foodb 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  test: ^1.24.0
  path: ^1.8.0
  dotenv: ^3.0.0
  foodb: ^0.13.0

dev_dependencies:
  pedantic: ^1.10.0

dependency_overrides:
  watcher: ^1.1.0
