name: foodb_test
description: Test suite to run against different flavour of foodb
version: 0.7.6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.16.0
  path: ^1.8.0
  dotenv: ^3.0.0
  foodb: ">=0.7.6"

dependency_overrides:
  foodb:
    path: ../foodb

dev_dependencies:
  pedantic: ^1.10.0
