name: foodb
description: A CouchDB warpper with dart implementation
version: 0.2.0
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  synchronized: ^3.0.0
  uri: ^1.0.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.3
  path: any
  test: any
