name: foodb_server
description: A server app using the shelf package and Docker.
version: 0.10.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dotenv: ^3.0.0
  args: ^2.0.0
  shelf:
    git:
      url: https://github.com/feedmepos/shelf
      path: pkgs/shelf
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.2
  foodb:
    git:
      url: git@github.com:feedmepos/foodb.git
      path: foodb
      ref: feat/yr/flutter-3.22

dependency_overrides:
  foodb_test:
    git:
      url: git@github.com:feedmepos/foodb.git
      path: foodb_test
      ref: feat/yr/flutter-3.22
  foodb:
    git:
      url: git@github.com:feedmepos/foodb.git
      path: foodb
      ref: feat/yr/flutter-3.22
  shelf:
    git:
      url: https://github.com/feedmepos/shelf
      path: pkgs/shelf
  # shelf:
  #   path: C://Users//user//Documents//GitHub//shelf//pkgs//shelf

dev_dependencies:
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.15.0
  foodb_test: ">=0.7.4"
